baseURL = "https://franquil.github.io/"
languageCode = "zh-cn"
DefaultContentLanguage = "zh-cn"
title = "大国笔记"
theme = "hugo-kiera"
paginate = 10
googleAnalytics = "UA-51312542-3"
publishDir = "docs" # deploy via github pages at /docs folder

[author]
  name = "Franquil"
  github = "franquil"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 0
 
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags"
    weight = 10

[params]
  description = "大国笔记，以记录和学习为目的的简要记录内容。"
  dateFormat = "2006-01-02"
  tagline = "以记录和学习为目的的笔记。"

